### ISSUE TITLE
ZIP compression

### ISSUE THREAD

**Issue by sz00gun** [Real-Gecko/Filemin#24]
Thank you for this superb module, however is possible to make a ZIP compression of files? and what to do to see a /home catalog?

**Comment by Real-Gecko** [comment]
Zip compression is now only supported for unarchiving, I'll look into implementing other compression methods while compressing.
To get out of $HOME you need to navigate to `Webmin->Webmin Users->$YOUR_USERN_NAME->Available Webmin modules (in addition to those from group)` and click `Filemin`. You will see "Filemin access control options", input desired paths here, like `/usr/share/webmin`, one per line. If you want a full FS access then input only one option "$ROOT" there, and you'll be happy. However you must note that you'll work with your user's permissions, so trying to navigate to other user's $HOME or to edit any config file belongin to 'root' will raise https://www.youtube.com/watch?v=2dZy3cd9KFY

**Comment by sz00gun** [comment]
I already should have an access for it, because I logged as a root, 
![filemin](https://cloud.githubusercontent.com/assets/7549566/8694448/03a1ba9e-2ad7-11e5-9419-d0ce34f0949c.jpg)

Where can I see: Filemin access control options ? I cannot find it.

**Comment by Real-Gecko** [comment]
Click on "Filemin".

**Comment by sz00gun** [comment]
Ohhh my bad... thank you, however I put $ROOT in the Filemin access control options and I can see /home directory now.... but I cannot access there.

Please advise
![filemin2](https://cloud.githubusercontent.com/assets/7549566/8696533/ef8409e6-2ae4-11e5-9192-ab5f18d095d5.jpg)
![filemin2a](https://cloud.githubusercontent.com/assets/7549566/8696535/f37955ce-2ae4-11e5-88bd-2f54372dbaba.jpg)

**Comment by Real-Gecko** [comment]
OMG, now it is my bad :D New listing algorithm does not work with symlinks and mount points, will fix that soon.

**Comment by Real-Gecko** [comment]
Symlinks and mount points were fixed in 0.9.3.

**Comment by Goeny** [comment]
I have a cifs mount point which doesn't work in filemin 0.9.3. So i think it is not fixed completely in 0.9.3

**Comment by Real-Gecko** [comment]
What about other mount points?

**Comment by Goeny** [comment]
Other mount points not working either..

**Comment by Real-Gecko** [comment]
What was your update method? Webmin interface?

**Comment by Goeny** [comment]
no, git pull.
Just did a new pull, was up-to-date

**Comment by Real-Gecko** [comment]
symlinks?

**Comment by Real-Gecko** [comment]
What's the version in module.info?

**Comment by Goeny** [comment]
symlinks don't seem to work either.
Version is module.info = 0.9.3

desc_ru.UTF-8= has no value. (Probably has nothing to do with this problem, just mentioning)

**Comment by Real-Gecko** [comment]
What are the lines 39 and 40 in index.cgi?

**Comment by Goeny** [comment]
```
# Get info about directory entries
@info = map { [ $_, stat($_), mimetype($_), -d $_ ] } @list;
```

have to mention,... syntaxhighlighting, and line numbers are not showing,.. so have to count lines manually.. :-(

**Comment by Real-Gecko** [comment]
Try to completely reinstall module, it may be some caching issues.

**Comment by Goeny** [comment]
Should i reinstall with git clone, or using the webmin installer?

**Comment by Real-Gecko** [comment]
Remove module completely from Webmin interfaces
Download either wbm or deb from here https://github.com/Real-Gecko/filemin/tree/master/distrib
for preferred method of installation.
I'd recommed deb if you're on Debian or Ubuntu, it removes any confusion about module update.

**Comment by Real-Gecko** [comment]
BTW zip compression is ready, will be in version 0.9.4 ;-)

**Comment by Goeny** [comment]
reinstalled using deb file. (I am on Debian 7.8.0)
Still not working...

**Comment by Real-Gecko** [comment]
Do you have any options to test on another machine?

**Comment by Goeny** [comment]
I can create a VM with a fresh install later today.
Will let you know if it works.

**Comment by Real-Gecko** [comment]
Syntax highlighting will be in next release, it will select highlighting according to file type.
What theme do you use? Authentic?

**Comment by Goeny** [comment]
yes

**Comment by Goeny** [comment]
Did a full system reboot, mount points and symlinks seem to work now.
Still have "question marks"  as icons for those, but they do link to the correct folders/drives.

Will reinstall on other machines aswell..

**Comment by Real-Gecko** [comment]
Question mark will be, I'll symlink `inode-mount-point` icon to `inode-directory` icon in next release, hope that will not cause any confusion :)

**Comment by Goeny** [comment]
Great.. Thanks for the support :)

**Comment by Real-Gecko** [comment]
Added in 0.9.4.
