### ISSUE TITLE
Not possible to browse into some folders

### ISSUE THREAD

**Issue by g7rau** [Real-Gecko/Filemin#82]
When browsing some folders in filemin i.e. subfolders within  home/files$ I get the error:  home/files$/home/files$/stuff No such file or directory
I presume it is the $ causing the issue when drilling down to subfolders within the folder? All other folders access are fine. The $ is used to hide the share on windows systems and although I could just map these differently in Samba I prefer to have the folder structures the same.

Regards

Dave

**Comment by Real-Gecko** [comment]
Yep, $ sign is usually used in variables names in Perl, I think you're right and it causes the trouble. I'll look into how can this be avoided, so you can have $ in file/folder names.

**Comment by erambour** [comment]
Hi, I've just noticed a similar problem with pathnames that contains a **#** character.
As every work project folder we use is referenced with a **#** + 4 digit number, it means for us that 99% of our file system is not available thru this wonderful file manager.

That issue came while upgrading Webmin 1.770 to 1.780

Best Regards
Eric

(EDIT : Reloading the filemin-0.9.6.linux.wbm from here fixed this issue, but every Webmin upgrade i've made caused it)

**Comment by Real-Gecko** [comment]
I think this caused by some code changes made before 0.9.6.
Webmin now bundles Filemin, but I'm not sure which version of code is there.

**Comment by jcameron** [comment]
I think I see the cause of this - it was due to incorrect escaping of file paths. I've just checked in a fix.

**Comment by Real-Gecko** [comment]
Thanks, Jamie :)

**Comment by g7rau** [comment]
On 01/01/2016 01:32, Jamie Cameron wrote:

> I think I see the cause of this - it was due to incorrect escaping of 
> file paths. I've just checked in a fix.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Real-Gecko/filemin/issues/82#issuecomment-168273246.

Hi Jamie

I saw the update 1.780 and now I can browse into a folder with a $ 
character in it but further browsing into sub folders the link is 
broken, it shows as:
https://10.0.0.1:10000/filemin/index.cgi?path=/home/apps2$/home/apps2$/utils
whereas the link path should be
https://10.0.0.1:10000/filemin/index.cgi?path=/home/apps2$/utils

Regards

Dave

## 

..........................
Dave Edwards (G7RAU)
email:
dave@g7rau.co.uk
Web:
http://g7rau.demon.co.uk/
..........................

**Comment by jcameron** [comment]
I just tested this with Webmin 1.780, and I could browse into subfolders just fine.

**Comment by Real-Gecko** [comment]
Fixed.

**Comment by g7rau** [comment]
On 10/01/2016 18:10, Jamie Cameron wrote:

> I just tested this with Webmin 1.780, and I could browse into 
> subfolders just fine.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Real-Gecko/filemin/issues/82#issuecomment-170376018.
> 
> Hi Jamie

Rebooted the server here after making sure everything was up to date and 
still the same issue, a duplication of the path in the link querystring. 
I have changed my folder names to remove the $ now as I can still have 
the $ in the samba config folder name but maybe some others will still 
have this issue. I have left one folder in case you want any screenshots 
for debugging etc.

Cheers

Dave

## 

..........................
Dave Edwards (G7RAU)
email:
dave@g7rau.co.uk
Web:
http://g7rau.demon.co.uk/
..........................

**Comment by Real-Gecko** [comment]
Can you post the screenshot?

**Comment by g7rau** [comment]
On 17/01/2016 16:31, Real-Gecko wrote:

> Can you post the screenshot?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Real-Gecko/filemin/issues/82#issuecomment-172347223.

Screenshot attached.

## 

..........................
Dave Edwards (G7RAU)
email:
dave@g7rau.co.uk
Web:
http://g7rau.demon.co.uk/
..........................

**Comment by Real-Gecko** [comment]
I see none.

**Comment by g7rau** [comment]
On 17/01/2016 16:50, Real-Gecko wrote:

> I see none.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Real-Gecko/filemin/issues/82#issuecomment-172349655.

OK, must have been removed. file link: 
http://g7rau.demon.co.uk/temp/filemin.jpg
The mouse not in the screenshot but the link path on the bottom showing 
the duplication.

Cheers

Dave

## 

..........................
Dave Edwards (G7RAU)
email:
dave@g7rau.co.uk
Web:
http://g7rau.demon.co.uk/
..........................

**Comment by Real-Gecko** [comment]
Version 1.0.0 is out. Now you can put "thousands of $$" into you file names :D Enjoy.
![2](https://cloud.githubusercontent.com/assets/2231969/12544506/f2d37064-c364-11e5-9554-e2cadf57faa9.png)

**Comment by g7rau** [comment]
On 25/01/2016 07:10, Real-Gecko wrote:

> Version 1.0.0 is out. Now you can put "thousands of $$" into you file 
> names :D Enjoy.
> 2 
> https://cloud.githubusercontent.com/assets/2231969/12544506/f2d37064-c364-11e5-9554-e2cadf57faa9.png
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Real-Gecko/filemin/issues/82#issuecomment-174422078.

Many thanks. I have left my spare drive mounted as /home/games$ to test.

FYI, when browsing around other folders I noticed another char, the hash 
"#" is removed from the path and therefore the link fails. For me this 
is not an issue but might be for others. I never created this folder, it 
was created in a c# conversion option for some projects in a csharp 
application so maybe it might be reported in the future by others.

Cheerio

Dave

## 

..........................
Dave Edwards (G7RAU)
email:
dave@g7rau.co.uk
Web:
http://g7rau.demon.co.uk/
..........................

**Comment by Real-Gecko** [comment]
OK, I'll keep in mind issue about '#' sign and reopen issue to fix it in next release.

**Comment by Real-Gecko** [comment]
Fixed in 1.1.0
